### ISSUE TITLE
Nachrichten werden beim Sterben nicht angezeigt 

### ISSUE THREAD

**Issue by chrischivlog** [ifheroes/InfinityHeroes-FFO#2]
Wenn ein Spieler stirbt gibt es keine Nachricht mehr.

**Comment by IDev-mc** [comment]
Schau hier du Vogel... [hier](https://github.com/ifheroes/InfinityHeroes-FFO/commit/2c7332d2289cd15fdf03026dd49567cdb4c22fbd)
